//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Figaro.Web.ApplicationServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MemberResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MemberResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Figaro.Web.ApplicationServices.MemberResource", typeof(MemberResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to membership.
        /// </summary>
        internal static string ContainerAlias {
            get {
                return ResourceManager.GetString("ContainerAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name cannot be a null or empty string..
        /// </summary>
        internal static string FigaroMembership_UserName_NullOrEmpty {
            get {
                return ResourceManager.GetString("FigaroMembership_UserName_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username: &apos;.
        /// </summary>
        internal static string FigaroMembershipProvider_InvalidUsername {
            get {
                return ResourceManager.GetString("FigaroMembershipProvider_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.sleepycat.com/2002/dbxml.
        /// </summary>
        internal static string FilenameMetaDataNamespace {
            get {
                return ResourceManager.GetString("FilenameMetaDataNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUsersByNameCount.
        /// </summary>
        internal static string GetUsersByNameCount {
            get {
                return ResourceManager.GetString("GetUsersByNameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordAnswer.
        /// </summary>
        internal static string PasswordAnswer {
            get {
                return ResourceManager.GetString("PasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordQuestion.
        /// </summary>
        internal static string PasswordQuestion {
            get {
                return ResourceManager.GetString("PasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /FigaroMembershipUser/Email.
        /// </summary>
        internal static string PathEmail {
            get {
                return ResourceManager.GetString("PathEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /FigaroMembershipUser/PathIsLockedOut.
        /// </summary>
        internal static string PathIsLockedOut {
            get {
                return ResourceManager.GetString("PathIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /FigaroMembershipUser/LastActivityDate.
        /// </summary>
        internal static string PathLastActivity {
            get {
                return ResourceManager.GetString("PathLastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /FigaroMembershipUser/Password.
        /// </summary>
        internal static string PathPassword {
            get {
                return ResourceManager.GetString("PathPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /FigaroMembershipUser/ProviderUserKey.
        /// </summary>
        internal static string PathUserKey {
            get {
                return ResourceManager.GetString("PathUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /FigaroMembershipUser/UserName.
        /// </summary>
        internal static string PathUserName {
            get {
                return ResourceManager.GetString("PathUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace value of node  doc($doc)/FigaroMembershipUser/PasswordAnswer with $answer.
        /// </summary>
        internal static string QueryChangePasswordAnswer {
            get {
                return ResourceManager.GetString("QueryChangePasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace value of node doc($doc)/FigaroMembershipUser/PasswordQuestion with $question.
        /// </summary>
        internal static string QueryChangePasswordQuestion {
            get {
                return ResourceManager.GetString("QueryChangePasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace value of node doc($doc)/FigaroMembershipUser/PasswordQuestion with $question,
        ///replace value of node  doc($doc)/FigaroMembershipUser/PasswordAnswer with $answer.
        /// </summary>
        internal static string QueryChangePasswordQuestionAndAnswer {
            get {
                return ResourceManager.GetString("QueryChangePasswordQuestionAndAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x at $count in collection(&apos;membership&apos;) where $x/FigaroMembershipUser/Email = $email return $x.
        /// </summary>
        internal static string QueryCountUsersByEmail {
            get {
                return ResourceManager.GetString("QueryCountUsersByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x at $count in collection(&apos;membership&apos;) where $x/FigaroMembershipUser/UserName = $user return $x.
        /// </summary>
        internal static string QueryCountUsersByUserName {
            get {
                return ResourceManager.GetString("QueryCountUsersByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x in collection(&apos;membership&apos;) where {0} return {1}.
        /// </summary>
        internal static string QueryGet {
            get {
                return ResourceManager.GetString("QueryGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x at $count in collection(&apos;membership&apos;) where $count = ($i to $j) return $x.
        /// </summary>
        internal static string QueryGetAllUsersPage {
            get {
                return ResourceManager.GetString("QueryGetAllUsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x in collection(&apos;membership&apos;) where {0} return $x/dbxml:metadata(&apos;dbxml:name&apos;).
        /// </summary>
        internal static string QueryGetFileName {
            get {
                return ResourceManager.GetString("QueryGetFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xs:string(doc($doc)/FigaroMembershipUser/Password).
        /// </summary>
        internal static string QueryGetPassword {
            get {
                return ResourceManager.GetString("QueryGetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x in collection(&apos;membership&apos;) where {0} return $x/FigaroMembersipUser/Password.
        /// </summary>
        internal static string QueryGetPassword1 {
            get {
                return ResourceManager.GetString("QueryGetPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xs:string(doc($doc)/FigaroMembershipUser/PasswordAnswer).
        /// </summary>
        internal static string QueryGetPasswordAnswer {
            get {
                return ResourceManager.GetString("QueryGetPasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x in collection(&apos;membership&apos;) where {0} return $x.
        /// </summary>
        internal static string QueryGetUser {
            get {
                return ResourceManager.GetString("QueryGetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x in collection(&apos;membership&apos;) where $x/FigaroMembershipUser[Email = $email] return dbxml:metadata(&quot;dbxml:name&quot;,$x).
        /// </summary>
        internal static string QueryGetUserNameByEmail {
            get {
                return ResourceManager.GetString("QueryGetUserNameByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x in collection(&apos;membership&apos;) where $x/FigaroMembershipUser[Email = $email] return count($x).
        /// </summary>
        internal static string QueryGetUsersByEmailCount {
            get {
                return ResourceManager.GetString("QueryGetUsersByEmailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count(collection(&apos;membership&apos;)/FigaroMembershipUser[Email = $email]).
        /// </summary>
        internal static string QueryGetUsersByEmailCount1 {
            get {
                return ResourceManager.GetString("QueryGetUsersByEmailCount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x at $count in collection(&apos;membership&apos;) where $x/FigaroMembershipUser[Email = $email] and $count = ($i to $j) return $x.
        /// </summary>
        internal static string QueryGetUsersByEmailPage {
            get {
                return ResourceManager.GetString("QueryGetUsersByEmailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count(collection(&apos;membership&apos;)/FigaroMembershipUser[UserName = $user]).
        /// </summary>
        internal static string QueryGetUsersByNameCount {
            get {
                return ResourceManager.GetString("QueryGetUsersByNameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x at $count in collection(&apos;membership&apos;) where $x/FigaroMembershipUser[UserName = $user] and $count = ($i to $j) return $x.
        /// </summary>
        internal static string QueryGetUsersByNamePage {
            get {
                return ResourceManager.GetString("QueryGetUsersByNamePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x at $count in collection(&apos;membership&apos;) where $count = ({0}) return $x.
        /// </summary>
        internal static string QueryGetUsersPage {
            get {
                return ResourceManager.GetString("QueryGetUsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace value of node doc($doc){1} with \&quot;{2}\&quot;.
        /// </summary>
        internal static string QueryReplace {
            get {
                return ResourceManager.GetString("QueryReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace value of node doc($doc)/FigaroMembershipUser/Password with $pass.
        /// </summary>
        internal static string QueryReplacePassword {
            get {
                return ResourceManager.GetString("QueryReplacePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace value of node doc($doc)/FigaroMembershipUser/PasswordAnswer with \&quot;{1}\&quot;.
        /// </summary>
        internal static string QueryReplacePasswordAnswer {
            get {
                return ResourceManager.GetString("QueryReplacePasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace value of node doc($doc)/FigaroMembershipUser/PasswordQuestion with \&quot;{1}\&quot;.
        /// </summary>
        internal static string QueryReplacePasswordQuestion {
            get {
                return ResourceManager.GetString("QueryReplacePasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace value of node doc($doc){0} with $val.
        /// </summary>
        internal static string QueryReplaceValue {
            get {
                return ResourceManager.GetString("QueryReplaceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace value of node doc($doc)/FigaroMembershipUser/Password with $val.
        /// </summary>
        internal static string QuerySetNewPassword {
            get {
                return ResourceManager.GetString("QuerySetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace value of node doc($doc)/FigaroMembershipUser/PathIsLockedOut with $locked.
        /// </summary>
        internal static string QueryUnlockUser {
            get {
                return ResourceManager.GetString("QueryUnlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace value of node doc($doc)/FigaroMembershipUser/LastActivityDate with $date.
        /// </summary>
        internal static string QueryUpdateUserOnline {
            get {
                return ResourceManager.GetString("QueryUpdateUserOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x in collection(&apos;membership&apos;) where $x/FigaroMembershipUser[UserName = $user] and $x/FigaroMembershipUser[Password = $pwd] return $x.
        /// </summary>
        internal static string QueryValidateUser {
            get {
                return ResourceManager.GetString("QueryValidateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FigaroMembershipProvider.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $key.
        /// </summary>
        internal static string VariableKey {
            get {
                return ResourceManager.GetString("VariableKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $pwd.
        /// </summary>
        internal static string VariablePwd {
            get {
                return ResourceManager.GetString("VariablePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $user.
        /// </summary>
        internal static string VariableUser {
            get {
                return ResourceManager.GetString("VariableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $x.
        /// </summary>
        internal static string VariableX {
            get {
                return ResourceManager.GetString("VariableX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $y.
        /// </summary>
        internal static string VariableY {
            get {
                return ResourceManager.GetString("VariableY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $x/FigaroMembershipUser[UserName = $user].
        /// </summary>
        internal static string WhereUserName {
            get {
                return ResourceManager.GetString("WhereUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.bdbxml.net/web/membership/2009/05/.
        /// </summary>
        internal static string xmlns {
            get {
                return ResourceManager.GetString("xmlns", resourceCulture);
            }
        }
    }
}
