//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Figaro.Web.ApplicationServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProfileResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Figaro.Web.ApplicationServices.ProfileResource", typeof(ProfileResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string ContextUserName {
            get {
                return ResourceManager.GetString("ContextUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x at $count in collection(&apos;profile&apos;) where {0} return $x.
        /// </summary>
        internal static string DocCount {
            get {
                return ResourceManager.GetString("DocCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x in collection(&apos;profile&apos;) where {0} return $x&quot;.
        /// </summary>
        internal static string DocQuery {
            get {
                return ResourceManager.GetString("DocQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $x/FigaroUserProfile[dxml:metadata(&apos;db:name&apos;).
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x in collection(&apos;profile&apos;) where {0} return {1}.
        /// </summary>
        internal static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for $x at $count in collection(&apos;profile&apos;) where {0} $count = ({1}) return $x.
        /// </summary>
        internal static string GetProfilesPage {
            get {
                return ResourceManager.GetString("GetProfilesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAuthenticated.
        /// </summary>
        internal static string IsAuthenticated {
            get {
                return ResourceManager.GetString("IsAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastActivityDate.
        /// </summary>
        internal static string LastActivityDate {
            get {
                return ResourceManager.GetString("LastActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastUpdatedTime.
        /// </summary>
        internal static string LastUpdatedTime {
            get {
                return ResourceManager.GetString("LastUpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boolean($x/FigaroUserProfile[dbxml:metadata(&apos;{0}:{1}&apos;)]).
        /// </summary>
        internal static string MetadataBoolean {
            get {
                return ResourceManager.GetString("MetadataBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.sleepycat.com/2002/dbxml.
        /// </summary>
        internal static string MetadataFileNameNS {
            get {
                return ResourceManager.GetString("MetadataFileNameNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collection(&apos;profile&apos;)/*[dbxml:metadata(&apos;{0}:{1}&apos;)=&apos;{2}&apos;].
        /// </summary>
        internal static string MetadataLookup {
            get {
                return ResourceManager.GetString("MetadataLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc(&quot;dbxml:/profile/{0}&quot;)/FigaroUserProfile[dbxml:metadata(&apos;ts:{1}&apos;) = &quot;{2}&quot;].
        /// </summary>
        internal static string MetadataUpdate {
            get {
                return ResourceManager.GetString("MetadataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $x/FigaroUserProfile[dbxml:metadata(&apos;{0}:{1}&apos;) {2} {3}].
        /// </summary>
        internal static string MetaDataWhere {
            get {
                return ResourceManager.GetString("MetaDataWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let $prop := for $x in doc(&quot;dbxml:/profile/{0}&quot;)/FigaroUserProfile/Property where $x/@name = $name return $x
        ///return (if (exists($prop)) then 
        ///	replace value of node $prop with {1}
        ///else
        ///	insert nodes {1} as last into doc(&quot;dbxml:/profile/{0}&quot;)/FigaroUserProfile).
        /// </summary>
        internal static string PropertyUpsert {
            get {
                return ResourceManager.GetString("PropertyUpsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FigaroUserProfile.
        /// </summary>
        internal static string RootNode {
            get {
                return ResourceManager.GetString("RootNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FigaroProfileReader.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.bdbxml.net/web/profile/2009/05/.
        /// </summary>
        internal static string xmlns {
            get {
                return ResourceManager.GetString("xmlns", resourceCulture);
            }
        }
    }
}
